package com.payitezy.domain;

// Generated 7 May, 2016 4:24:03 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * ApiDetails generated by hbm2java
 */
@Entity
@Table(name = "api_details", catalog = "payitezy")
public class ApiDetails extends AbstractDomain implements java.io.Serializable {

    private String apiCode;
    private String apiName;
    private String status;
    private Date createdDate;
    private int apiCount;
    private Set<ApiKeys> apiKeyses = new HashSet<ApiKeys>(0);
    private Set<ApiOperatorMargin> apiOperatorMargins = new HashSet<ApiOperatorMargin>(0);
    private Set<ApiCircle> apiCircles = new HashSet<ApiCircle>(0);

    public ApiDetails() {
    }

    public ApiDetails(final String apiCode, final Integer apiCount, final String apiName, final String status, final Date createdDate) {
        this.apiCode = apiCode;
        this.apiName = apiName;
        this.status = status;
        this.createdDate = createdDate;
        this.apiCount = apiCount;
    }

    public ApiDetails(final String apiCode, final String apiName, final String status, final Integer apiCount, final Date createdDate,
            final Set<ApiKeys> apiKeyses, final Set<ApiOperatorMargin> apiOperatorMargins, final Set<ApiCircle> apiCircles) {
        this.apiCode = apiCode;
        this.apiName = apiName;
        this.status = status;
        this.createdDate = createdDate;
        this.apiCount = apiCount;
        this.apiKeyses = apiKeyses;
        this.apiOperatorMargins = apiOperatorMargins;
        this.apiCircles = apiCircles;
    }

    /**
     * @return the apiCircles
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "apiDetails")
    public Set<ApiCircle> getApiCircles() {
        return apiCircles;
    }

    @Column(name = "api_code", nullable = false, length = 45)
    public String getApiCode() {
        return apiCode;
    }

    /**
     * @return the apiCount
     */

    @Column(name = "api_count", nullable = false)
    public int getApiCount() {
        return apiCount;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "apiDetails")
    public Set<ApiKeys> getApiKeyses() {
        return apiKeyses;
    }

    @Column(name = "api_name", nullable = false, length = 45)
    public String getApiName() {
        return apiName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "apiDetails")
    public Set<ApiOperatorMargin> getApiOperatorMargins() {
        return apiOperatorMargins;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    /**
     * @param apiCircles
     *            the apiCircles to set
     */

    public void setApiCircles(final Set<ApiCircle> apiCircles) {
        this.apiCircles = apiCircles;

    }

    public void setApiCode(final String apiCode) {
        this.apiCode = apiCode;
    }

    /**
     * @param apiCount
     *            the apiCount to set
     */
    public void setApiCount(final int apiCount) {
        this.apiCount = apiCount;
    }

    public void setApiKeyses(final Set<ApiKeys> apiKeyses) {
        this.apiKeyses = apiKeyses;
    }

    public void setApiName(final String apiName) {
        this.apiName = apiName;
    }

    public void setApiOperatorMargins(final Set<ApiOperatorMargin> apiOperatorMargins) {
        this.apiOperatorMargins = apiOperatorMargins;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
