package com.payitezy.domain;

// Generated 7 May, 2016 4:24:03 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApiKeys generated by hbm2java
 */
@Entity
@Table(name = "api_keys", catalog = "payitezy")
public class ApiKeys extends AbstractDomain implements java.io.Serializable {

	private ApiDetails apiDetails;
	private String keyName;
	private String keyValue;
	private String status;
	private Date createdDate;

	public ApiKeys() {
	}

	public ApiKeys( ApiDetails apiDetails, String keyName,
			String keyValue, String status, Date createdDate) {
		this.apiDetails = apiDetails;
		this.keyName = keyName;
		this.keyValue = keyValue;
		this.status = status;
		this.createdDate = createdDate;
	}
 
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "api_details_id", nullable = false)
	public ApiDetails getApiDetails() {
		return this.apiDetails;
	}

	public void setApiDetails(ApiDetails apiDetails) {
		this.apiDetails = apiDetails;
	}

	@Column(name = "key_name", nullable = false, length = 100)
	public String getKeyName() {
		return this.keyName;
	}

	public void setKeyName(String keyName) {
		this.keyName = keyName;
	}

	@Column(name = "key_value", nullable = false, length = 100)
	public String getKeyValue() {
		return this.keyValue;
	}

	public void setKeyValue(String keyValue) {
		this.keyValue = keyValue;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
