package com.payitezy.domain;

// Generated 7 May, 2016 4:24:03 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.*;

/**
 * ApiOperatorMargin generated by hbm2java
 */
@Entity
@Table(name = "api_operator_margin", catalog = "payitezy")
public class ApiOperatorMargin extends AbstractDomain implements java.io.Serializable {

    private PayitezyOperator payitezyOperator;
    private ApiDetails apiDetails;
    private String apiOperatorId;
    private Double margin;
    private String rechargesStatus;
    private String status;
    private Date createdDate;
    private String mobileOperatorCheck;

    public ApiOperatorMargin() {
    }

    public ApiOperatorMargin(final PayitezyOperator payitezyOperator, final ApiDetails apiDetails, final String apiOperatorId,
            final Double margin, final String rechargesStatus, final String status, final Date createdDate, final String mobileOperatorCheck) {
        this.payitezyOperator = payitezyOperator;
        this.apiDetails = apiDetails;
        this.apiOperatorId = apiOperatorId;
        this.margin = margin;
        this.rechargesStatus = rechargesStatus;
        this.status = status;
        this.createdDate = createdDate;
        this.mobileOperatorCheck = mobileOperatorCheck;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "api_details_id", nullable = false)
    public ApiDetails getApiDetails() {
        return apiDetails;
    }

    @Column(name = "api_operator_id", nullable = false, length = 45)
    public String getApiOperatorId() {
        return apiOperatorId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "margin", nullable = false, length = 45)
    public Double getMargin() {
        return margin;
    }

    @Column(name = "mobile_operator_check", nullable = false, length = 45)
    public String getMobileOperatorCheck() {
        return mobileOperatorCheck;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "payitezy_operator_id", nullable = false)
    public PayitezyOperator getPayitezyOperator() {
        return payitezyOperator;
    }

    @Column(name = "recharges_status", nullable = false, length = 45)
    public String getRechargesStatus() {
        return rechargesStatus;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setApiDetails(final ApiDetails apiDetails) {
        this.apiDetails = apiDetails;
    }

    public void setApiOperatorId(final String apiOperatorId) {
        this.apiOperatorId = apiOperatorId;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setMargin(final Double margin) {
        this.margin = margin;
    }

    public void setMobileOperatorCheck(final String mobileOperatorCheck) {
        this.mobileOperatorCheck = mobileOperatorCheck;
    }

    public void setPayitezyOperator(final PayitezyOperator payitezyOperator) {
        this.payitezyOperator = payitezyOperator;
    }

    public void setRechargesStatus(final String rechargesStatus) {
        this.rechargesStatus = rechargesStatus;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
