package com.payitezy.domain;

// Generated 7 May, 2016 4:24:03 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClickTransaction generated by hbm2java
 */
@Entity
@Table(name = "click_transaction", catalog = "payitezy")
public class ClickTransaction extends AbstractDomain implements java.io.Serializable {

	private Users users;
	private Merchant merchant;
	private History history;
	private Date createdDate;
	private String status;
	private String urlClicked;
	private String clickedSource;
	private String orderStatus;
	private String clickedTarget;
	private String clickedTargetId;

	public ClickTransaction() {
	}

	public ClickTransaction( Users users, Merchant merchant,
			History history, Date createdDate, String status,
			String urlClicked, String clickedSource, String orderStatus,
			String clickedTarget, String clickedTargetId) {
		
		this.users = users;
		this.merchant = merchant;
		this.history = history;
		this.createdDate = createdDate;
		this.status = status;
		this.urlClicked = urlClicked;
		this.clickedSource = clickedSource;
		this.orderStatus = orderStatus;
		this.clickedTarget = clickedTarget;
		this.clickedTargetId = clickedTargetId;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_id", nullable = false)
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "history_id", nullable = false)
	public History getHistory() {
		return this.history;
	}

	public void setHistory(History history) {
		this.history = history;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "url_clicked", nullable = false, length = 45)
	public String getUrlClicked() {
		return this.urlClicked;
	}

	public void setUrlClicked(String urlClicked) {
		this.urlClicked = urlClicked;
	}

	@Column(name = "clicked_source", nullable = false, length = 45)
	public String getClickedSource() {
		return this.clickedSource;
	}

	public void setClickedSource(String clickedSource) {
		this.clickedSource = clickedSource;
	}

	@Column(name = "order_status", nullable = false, length = 45)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "clicked_target", nullable = false, length = 45)
	public String getClickedTarget() {
		return this.clickedTarget;
	}

	public void setClickedTarget(String clickedTarget) {
		this.clickedTarget = clickedTarget;
	}

	@Column(name = "clicked_target_id", nullable = false, length = 45)
	public String getClickedTargetId() {
		return this.clickedTargetId;
	}

	public void setClickedTargetId(String clickedTargetId) {
		this.clickedTargetId = clickedTargetId;
	}

}
