package com.payitezy.domain;

// Generated 7 May, 2016 4:24:03 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name = "history", catalog = "payitezy")
public class History extends AbstractDomain implements java.io.Serializable {

	private Users users;
	private String url;
	private Date createdDate;
	private String historyType;
	private String channel;
	private Set<ClickTransaction> clickTransactions = new HashSet<ClickTransaction>(
			0);

	public History() {
	}

	public History( Users users) {
		this.users = users;
	}

	public History( Users users, String url, Date createdDate,
			String historyType, String channel,
			Set<ClickTransaction> clickTransactions) {
		this.users = users;
		this.url = url;
		this.createdDate = createdDate;
		this.historyType = historyType;
		this.channel = channel;
		this.clickTransactions = clickTransactions;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "url", length = 45)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "history_type", length = 45)
	public String getHistoryType() {
		return this.historyType;
	}

	public void setHistoryType(String historyType) {
		this.historyType = historyType;
	}

	@Column(name = "channel", length = 45)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "history")
	public Set<ClickTransaction> getClickTransactions() {
		return this.clickTransactions;
	}

	public void setClickTransactions(Set<ClickTransaction> clickTransactions) {
		this.clickTransactions = clickTransactions;
	}

}
