package com.payitezy.domain;

// Generated 7 May, 2016 4:24:03 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * PayitezyOperator generated by hbm2java
 */
@Entity
@Table(name = "payitezy_operator", catalog = "payitezy")
public class PayitezyOperator extends AbstractDomain implements java.io.Serializable {

    private String payitezyOperatorCode;
    private String payitezyOperatorName;
    private String status;
    private Date createdDate;
    private Integer payitezyOperatorCount;
    private String payitezyOperatorType;
    private Set<ApiOperatorMargin> apiOperatorMargins = new HashSet<ApiOperatorMargin>(0);

    public PayitezyOperator() {
    }

    public PayitezyOperator(final String payitezyOperatorCode, final Integer payitezyOperatorCount, final String payitezyOperatorName,
            final String status, final String payitezyOperatorType) {
        this.payitezyOperatorCode = payitezyOperatorCode;
        this.payitezyOperatorName = payitezyOperatorName;
        this.payitezyOperatorType = payitezyOperatorType;
        this.status = status;
    }

    public PayitezyOperator(final String payitezyOperatorCode, final String payitezyOperatorName, final Integer payitezyOperatorCount,
            final String status, final String payitezyOperatorType, final Date createdDate, final Set<ApiOperatorMargin> apiOperatorMargins) {
        this.payitezyOperatorCode = payitezyOperatorCode;
        this.payitezyOperatorName = payitezyOperatorName;
        this.status = status;
        this.payitezyOperatorCount = payitezyOperatorCount;
        this.payitezyOperatorType = payitezyOperatorType;
        this.createdDate = createdDate;
        this.apiOperatorMargins = apiOperatorMargins;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "payitezyOperator")
    @OrderBy("margin DESC")
    public Set<ApiOperatorMargin> getApiOperatorMargins() {
        return apiOperatorMargins;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "payitezy_operator_code", nullable = false, length = 45)
    public String getPayitezyOperatorCode() {
        return payitezyOperatorCode;
    }

    /**
     * @return the payitezyOperatorCount
     */
    @Column(name = "payitezy_operator_count", nullable = false)
    public Integer getPayitezyOperatorCount() {
        return payitezyOperatorCount;
    }

    @Column(name = "payitezy_operator_name", nullable = false, length = 45)
    public String getPayitezyOperatorName() {
        return payitezyOperatorName;
    }

    @Column(name = "payitezy_operator_type", nullable = false, length = 45)
    public String getPayitezyOperatorType() {
        return payitezyOperatorType;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setApiOperatorMargins(final Set<ApiOperatorMargin> apiOperatorMargins) {
        this.apiOperatorMargins = apiOperatorMargins;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setPayitezyOperatorCode(final String payitezyOperatorCode) {
        this.payitezyOperatorCode = payitezyOperatorCode;
    }

    /**
     * @param payitezyOperatorCount
     *            the payitezyOperatorCount to set
     */

    public void setPayitezyOperatorCount(final Integer payitezyOperatorCount) {
        this.payitezyOperatorCount = payitezyOperatorCount;
    }

    public void setPayitezyOperatorName(final String payitezyOperatorName) {
        this.payitezyOperatorName = payitezyOperatorName;
    }

    public void setPayitezyOperatorType(final String payitezyOperatorType) {
        this.payitezyOperatorType = payitezyOperatorType;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
