package com.payitezy.domain;

// Generated Apr 28, 2016 4:56:47 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * RechargeTransaction generated by hbm2java
 */
@Entity
@Table(name = "recharge_transaction", catalog = "payitezy")
public class RechargeTransaction extends AbstractDomain implements java.io.Serializable {

    private Transaction transaction;
    private String rechargeTransactionCode;
    private String operatorNane;
    private String circleName;
    private BigDecimal amount;
    private String specialCode;
    private String rechargeType;
    private String mobileNumber;
    private String accountNumber;
    private String operatorId;
    private String circleId;
    private String adminCost;
    private String adminMargin;

    public RechargeTransaction() {
    }

    public RechargeTransaction(final String id, final Transaction transaction, final String rechargeTransactionCode,
            final String operatorNane, final String circleName, final BigDecimal amount, final String rechargeType,
            final String mobileNumber, final String accountNumber, final String adminCost, final String adminMargin) {
        this.id = id;
        this.transaction = transaction;
        this.rechargeTransactionCode = rechargeTransactionCode;
        this.operatorNane = operatorNane;
        this.circleName = circleName;
        this.amount = amount;
        this.rechargeType = rechargeType;
        this.mobileNumber = mobileNumber;
        this.accountNumber = accountNumber;
        this.adminCost = adminCost;
        this.adminMargin = adminMargin;
    }

    public RechargeTransaction(final String id, final Transaction transaction, final String rechargeTransactionCode,
            final String operatorNane, final String circleName, final BigDecimal amount, final String specialCode,
            final String rechargeType, final String mobileNumber, final String accountNumber, final String operatorId,
            final String circleId, final String adminCost, final String adminMargin) {
        this.id = id;
        this.transaction = transaction;
        this.rechargeTransactionCode = rechargeTransactionCode;
        this.operatorNane = operatorNane;
        this.circleName = circleName;
        this.amount = amount;
        this.specialCode = specialCode;
        this.rechargeType = rechargeType;
        this.mobileNumber = mobileNumber;
        this.accountNumber = accountNumber;
        this.operatorId = operatorId;
        this.circleId = circleId;
        this.adminCost = adminCost;
        this.adminMargin = adminMargin;
    }

    @Column(name = "account_number", nullable = false, length = 45)
    public String getAccountNumber() {
        return accountNumber;
    }

    @Column(name = "admin_cost", nullable = false, length = 45)
    public String getAdminCost() {
        return adminCost;
    }

    @Column(name = "admin_margin", nullable = false, length = 45)
    public String getAdminMargin() {
        return adminMargin;
    }

    @Column(name = "amount", nullable = false, precision = 7)
    public BigDecimal getAmount() {
        return amount;
    }

    @Column(name = "circle_id", length = 45)
    public String getCircleId() {
        return circleId;
    }

    @Column(name = "circle_name", nullable = false, length = 45)
    public String getCircleName() {
        return circleName;
    }

    @Column(name = "mobile_number", nullable = false, length = 45)
    public String getMobileNumber() {
        return mobileNumber;
    }

    @Column(name = "operator_id", length = 45)
    public String getOperatorId() {
        return operatorId;
    }

    @Column(name = "operator_nane", nullable = false, length = 45)
    public String getOperatorNane() {
        return operatorNane;
    }

    @Column(name = "recharge_transaction_code", nullable = false, length = 45)
    public String getRechargeTransactionCode() {
        return rechargeTransactionCode;
    }

    @Column(name = "recharge_type", nullable = false, length = 45)
    public String getRechargeType() {
        return rechargeType;
    }

    @Column(name = "special_code", length = 45)
    public String getSpecialCode() {
        return specialCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "transaction_id", nullable = false)
    public Transaction getTransaction() {
        return transaction;
    }

    public void setAccountNumber(final String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public void setAdminCost(final String adminCost) {
        this.adminCost = adminCost;
    }

    public void setAdminMargin(final String adminMargin) {
        this.adminMargin = adminMargin;
    }

    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    public void setCircleId(final String circleId) {
        this.circleId = circleId;
    }

    public void setCircleName(final String circleName) {
        this.circleName = circleName;
    }

    public void setMobileNumber(final String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public void setOperatorId(final String operatorId) {
        this.operatorId = operatorId;
    }

    public void setOperatorNane(final String operatorNane) {
        this.operatorNane = operatorNane;
    }

    public void setRechargeTransactionCode(final String rechargeTransactionCode) {
        this.rechargeTransactionCode = rechargeTransactionCode;
    }

    public void setRechargeType(final String rechargeType) {
        this.rechargeType = rechargeType;
    }

    public void setSpecialCode(final String specialCode) {
        this.specialCode = specialCode;
    }

    public void setTransaction(final Transaction transaction) {
        this.transaction = transaction;
    }

}
