package com.payitezy.domain;

// Generated Nov 6, 2014 9:21:29 PM by Hibernate Tools 3.6.0

import javax.persistence.*;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "payitezy")
public class Roles extends AbstractDomain implements java.io.Serializable {

    private String roleName;
    private String roleDetails;
    private String enable;
    private Users users;

    public Roles() {
    }

    public Roles(final String id, final String roleName, final String enable, final String roleDetails) {
        this.id = id;
        this.roleName = roleName;
        this.enable = enable;
        this.roleDetails = roleDetails;
    }

    public Roles(final String id, final String roleName, final String enable, final String roleDetails, final Users users) {
        this.id = id;
        this.roleName = roleName;
        this.roleDetails = roleDetails;
        this.enable = enable;
        this.users = users;
    }

    @Column(name = "enable", nullable = false, length = 45)
    public String getEnable() {
        return enable;
    }

    @Column(name = "role_details", length = 100)
    public String getRoleDetails() {
        return roleDetails;
    }

    @Column(name = "role_name", nullable = false, length = 45)
    public String getRoleName() {
        return roleName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id", nullable = false)
    public Users getUsers() {
        return users;
    }

    public void setEnable(final String enable) {
        this.enable = enable;
    }

    public void setRoleDetails(final String roleDetails) {
        this.roleDetails = roleDetails;
    }

    public void setRoleName(final String roleName) {
        this.roleName = roleName;
    }

    public void setUsers(final Users users) {
        this.users = users;
    }

}
